/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ApiAqiRouteImport } from './routes/api/aqi'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAqiRoute = ApiAqiRouteImport.update({
  id: '/api/aqi',
  path: '/api/aqi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/api/aqi': typeof ApiAqiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/api/aqi': typeof ApiAqiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/api/aqi': typeof ApiAqiRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/map' | '/api/aqi' | '/api/geocode' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/map' | '/api/aqi' | '/api/geocode' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/map'
    | '/api/aqi'
    | '/api/geocode'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ApiAqiRoute: typeof ApiAqiRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aqi': {
      id: '/api/aqi'
      path: '/api/aqi'
      fullPath: '/api/aqi'
      preLoaderRoute: typeof ApiAqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ApiAqiRoute: ApiAqiRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
